### ISSUE TITLE
Meeting location

### ISSUE THREAD

**Issue by troettge** [troettge/RN-Norway#12]
Anyone a good idea for a meeting location for us? Our meeting rooms (ILN) are booked for those dates.

**Comment by julienmayor** [comment]
I can book a meeting room in psychology that would be available on both November 19 and December 3 and 17. Happy to walk to the main campus if you find something more central!

**Comment by troettge** [comment]
Psych is fine by me.

**Comment by julienmayor** [comment]
V417 is booked until Christmas. It is in PSI - 4th floor, west wing!

**Comment by troettge** [comment]
Nice! Thank you Julien!
