### ISSUE TITLE
I have been completely swamped but I'm back now :)

### ISSUE THREAD

**Issue by sirileknes** [troettge/RN-Norway#19]
Looks like you guys have made a lot of progress, while I've been swamped with other work. A key person in the team had to abruptly quit at a really sensitive time and I had to step in, plus lots of extra work due to sick kids (own and team members'). Anyway, I'm back!

**Comment by troettge** [comment]
Welcome back. Check out the [Project Task Manager](https://github.com/troettge/RN-Norway/projects/1) to get an overview of things that happened / are happening. Tag people if you need input etc. One of the pressing things is feedback on the [website](https://github.com/troettge/RN-Norway/issues/3) until next meeting on next Tuesday.

**Comment by sirileknes** [comment]
Timo, I cannot see how to assign this to anyone.

**Comment by troettge** [comment]
You can tag people like this: @sirileknes

**Comment by sirileknes** [comment]
@troettge where do I do that to assign someone?
