### ISSUE TITLE
preview of mailing list is cropped

### ISSUE THREAD

**Issue by troettge** [troettge/RN-Norway#23]
@dsquintana The logo for the mailing list is kind of cropped (see images). Is it possible to change it to the round logo we use for twitter? Im sorry that I am stickler about these nitty gritty things haha. 

![image](https://user-images.githubusercontent.com/13022447/151830599-f0a57e2a-0f8c-47da-905a-22eaac4f7996.png)

<img width="589" alt="Screenshot 2022-01-31 at 17 15 16" src="https://user-images.githubusercontent.com/13022447/151830936-5b3373aa-967e-42e4-b9ed-09e35b3ae85e.png">

**Comment by dsquintana** [comment]
Good pick up, the logo has been updated
